---
title: "Dataquest COVID"
author: "Andrew Liu"
date: "2023-05-23"
output: html_document
This project's purpose is to analyze datasets relating to COVID-19.
---

```{r}
library(readr)
library(tidyverse)
library(dplyr)
covid_df <- read_csv("covid19.csv")
dim(covid_df)
vector_cols <- colnames(covid_df)
head(covid_df)

covid_df_all_states <- filter(covid_df,
                              Province_State == "All States")
covid_df_all_states_daily <- select(covid_df_all_states,
                                    Date, Country_Region, active, hospitalizedCurr, daily_tested, daily_positive)
covid_df_all_states_daily_sum <- covid_df_all_states_daily %>%
  group_by(Country_Region) %>%
  summarize(
    tested = sum(daily_tested),
    positive = sum(daily_positive),
    active = sum(active),
    hospitalized = sum(hospitalizedCurr)
  )
covid_df_all_states_daily_sum <- arrange(covid_df_all_states_daily_sum, -tested)
covid_top_10 <- head(covid_df_all_states_daily_sum, 10)

countries <- covid_top_10$Country_Region
tested_cases <- covid_top_10$tested
positive_cases <- covid_top_10$positive
active_cases <- covid_top_10$active
hospitalized_cases <- covid_top_10$hospitalized
#names(covid_top_10) <- countries

positive_cases/tested_cases
positive_tested_top_3 <- c("United Kingdom", "United States", "Turkey")

united_kingdom <- c(0.11, 1473672, 166909, 0, 0)
united_states <- c(0.10, 17282363, 1877179, 0, 0)
turkey <- c(0.08, 2031192, 163941, 2980960, 0)

covid_mat <- rbind(united_kingdom, united_states, turkey)
colnames(covid_mat) <- c("Ratio", "tested", "positive", "active", "hospitalized")

question <- "Which countries have had the highest number of positive cases against the number of tests?"
answer <- c("Positive tested cases" = positive_tested_top_3)

dataframe = list(c(covid_df), c(covid_df_all_states), c(covid_df_all_states_daily), c(covid_df_all_states_daily_sum), c(covid_top_10))
matrix = list(c(covid_mat))
vector = list(c(active_cases, countries, hospitalized_cases, positive_cases, positive_tested_top_3, tested_cases, turkey, united_kingdom, united_states, vector_cols))

data_structure_list <- list(dataframe = dataframe, matrix = matrix, vector = vector)

covid_analysis_list <- list(question, answer, data_structure_list)
covid_analysis_list[2]

```
```{r}

```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
